version: 0.0.0-dev
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/vprashar2929/cups-addon
codenotary: andrea_restello@yahoo.it
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
host_network: true
map:
  - data:rw
  - share:rw
init: false
ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
options:
  admin_username: "admin"
  admin_password: "admin"
schema:
  admin_username: str
  admin_password: password
startup: services
